---
- name: Config int réseau
  hosts: c1111
  # Passe l'étape permettant de récupérer des informations sur
  #   l'hôte pour gagner du temps
  gather_facts: false
  vars:
    interface_gigabit_1: "gi0/1/0"
    interface_gigabit_2: "gi0/1/1"
    interface_gigabit_3: "gi0/1/2"
    interface_gigabit_4: "gi0/1/3"
    vlan_1: "vlan 10"
    vlan_2: "vlan 20"
    vlan_3: "vlan 40"
    

  # Liste des tâches associées à notre Acte
  tasks:
    - name: Configuration de l'interface {{ interface_gigabit_1 }} en DHCP
      # On indique le nom du module
      cisco.ios.ios_config:
        lines:
          - interface gi0/0/0
          - description "Reseau IUT"
          - ip address dhcp
          - no shutdown
        parents: interface {{ interface_gigabit_1 }}
      register: interface_gigabit_1_result

    - name: Configuration de l'interface {{ interface_gigabit_2 }}
      # On indique le nom du module
      cisco.ios.ios_config:
        lines:
          - interface {{ vlan_1 }}
          - ip address 192.168.2.1 255.255.255.0
          - interface {{ interface_gigabit_2 }}
          - description "LAN_ENTREPRISE"
          - switchport mode access
          - switchport access {{ vlan_1 }}
          - no shutdown
        parents: interface {{ interface_gigabit_2 }}
      register: interface_gigabit_2_result
    
    - name: Configuration de l'interface {{ interface_gigabit_3 }}
      # On indique le nom du module
      cisco.ios.ios_config:
        lines:
          - interface {{ vlan_2 }}
          - ip address 192.168.3.1 255.255.255.0
          - interface {{ interface_gigabit_3 }}
          - description "LAN_DMZ"
          - switchport mode access
          - switchport access {{ vlan_2 }}
          - no shutdown
        parents: interface {{ interface_gigabit_3 }}
      register: interface_gigabit_3_result

    - name: Configuration de l'interface {{ interface_gigabit_4 }} en DHCP
      # On indique le nom du module
      cisco.ios.ios_config:
        lines:
          - interface {{ vlan_3 }}
          - ip address 192.168.4.1 255.255.255.0
          - interface {{ interface_gigabit_4 }}
          - description "LAN_ADMIN"
          - switchport mode access
          - switchport access {{ vlan_3 }}
          - no shutdown
        parents: interface {{ interface_gigabit_4 }}
      register: interface_gigabit_4_result

    - name: Affichage des résultats de la configuration
      debug:
        var: item
      loop:
        - "{{ interface_gigabit_1_result }}"
        - "{{ interface_gigabit_2_result }}"
        - "{{ interface_gigabit_3_result }}"
        - "{{ interface_gigabit_4_result }}"

