---
- name: Config des DHCP
  hosts: c1111
  # Passe l'étape permettant de récupérer des informations sur
  #   l'hôte pour gagner du temps
  gather_facts: false
  vars:
  - name_dhcp_entreprise: "lan_entreprise"
  - GSSN_entreprise: "192.168.2.0"
  - MSR_entreprise: "255.255.255.0"
  - Gateway_entreprise: "192.168.2.1"


  # Liste des tâches associées à notre Acte
  tasks:
    - name: Configuration du DHCP {{ name_dhcp_entreprise }}
      # On indique le nom du module
      cisco.ios.ios_config:
        lines:
        - ip dhcp pool {{ name_dhcp_entreprise }}
        - network {{ GSSN_entreprise }} {{ MSR_entreprise }} 
        - default-router {{ Gateway_entreprise }}
        - exit
      register: dhcp_result

    - name: Affichage des résultats de la configuration DHCP
      debug:
        var: item
      loop:
        - "{{ dhcp_result }}"

#- name: Serveur DHCP
#  hosts: c1111
#  gather_facts: false
#  vars:
#    network_1: "192.168.2.0 255.255.255.0"
#    network_2: "192.168.3.0 255.255.255.0"
#    network_3: "192.168.4.0 255.255.255.0"
#    gateway_1: "192.168.2.1"
#    gateway_2: "192.168.3.1"
#    gateway_3: "192.168.4.1"



#    - name: Enregistre la configuration
      # Module pour copier des fichiers
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/copy_module.html
 #     copy:
        # Source : ce que l'on a récupéré dans config
  #      content: " {{ config.stdout[0] }}"
        # Nom du fichier, le terme entre accolade est une variable
   #     dest: "show_run_{{ inventory_hostname }}.txt"
